---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Get Version of etesync-dav
  ansible.builtin.include_tasks:
    file: tasks/get_version_of_etesync_dav.yml

- name: Download etesync-dav
  ansible.builtin.include_tasks:
    file: download_etesync_dav.yml

- name: Setup Systemd service
  ansible.builtin.include_tasks:
    file: setup_systemd.yml
