---
- name: Run systemctl enable etesync-dav.service
  become: true
  ansible.builtin.systemd:
    name: 'etesync-dav.service'
    enabled: true
    state: 'started'
    daemon_reload: true

- name: Run systemctl restart etesync-dav.service
  become: true
  ansible.builtin.systemd:
    name: 'etesync-dav.service'
    enabled: true
    state: 'restarted'
